### ISSUE TITLE
xgboost isn't installed in Canvas/Illumidesk

### ISSUE THREAD

**Issue by davidbelliott1** [learn-co-curriculum/dsc-xgboost-lab#1]
### Canvas Link

https://learning.flatironschool.com/courses/4266/assignments/158609?module_item_id=338742

### Concern

xgboost isn't installed in Illumidesk, therefore the students can't run this in Canvas.

Please place a warning about this, or verbiage that tell the students to clone it down locally.

### Suggested Changes

Suggested change is to add "Please clone this locally and run it from your machine." or something along those lines.

**Comment by bpurdy-ds** [comment]
Note is there to tell the students to run locally. Closed commit https://github.com/learn-co-curriculum/dsc-xgboost-lab/issues/1#issue-1072671316
